import time
numeros = list(range(21))
print(f'=' * 35)
print(numeros)
print(f'=' * 35)
time.sleep(1)
print(f'=' * 35)
print('Ordem decrescente...')
print(f'=' * 35)
print('Preparando ordem decrescente...')
print(f'=' * 35)
time.sleep(1)
print('Ordem decrescente pronta') 
print(f'=' * 35)
print('rodando...')
print(f'=' * 35)
numbers = list(range(20, -1, -1))
print(numbers)
time.sleep(0.5)
print(f'=' * 35)
print('Ordem realizada com êxito!')
print(f'=' * 35)